The terminal tokens defined in the grammar:
TOKEN_OFFSET, FMPL_GC_COPIED, FLOAT, OBJ_TAG, TAG, STRING, SYMBOL, FN_TAG,
NAMESPACE_TAG, GRAMMAR_TAG

-- ============================================================
-- TOP-LEVEL STRUCTURE
-- ============================================================

<code> ::= [ <code> <exp> <optsemi>
             <code> <object_def> <optsemi>
             <code> <grammar_def> <optsemi> ]

<optsemi> ::= [ ';' ]

-- ============================================================
-- OBJECT DEFINITIONS (with optional namespacing)
-- ============================================================

<object_def> ::= <OBJECT> <qualified_tag> <olist> <sparse_str>
                 <OBJECT> <qualified_tag> <sparse_str>

-- Qualified names: foo, foo::bar, foo::bar::baz
<qualified_tag> ::= <TAG>
                    <qualified_tag> '::' <TAG>

<olist> ::= '(' <oexp_seq> ')'
            '(' ')'

<oexp_seq> ::= <TAG>
               <OBJ_TAG>
               <qualified_tag>
               <oexp_seq> ',' <TAG>
               <oexp_seq> ',' <OBJ_TAG>
               <oexp_seq> ',' <qualified_tag>
               <oexp_seq> <TAG>
               <oexp_seq> <OBJ_TAG>
               <oexp_seq> <qualified_tag>
               <oexp_seq> <error>

<sparse_str> ::= '{' '}'
                 '{' <binding_list> '}'

-- ============================================================
-- BINDINGS (properties and methods)
-- Scope markers (.#public, .#private) are positional:
-- all subsequent bindings inherit that visibility until next marker
-- ============================================================

<binding_list> ::= <binding> <optsemi>
                   <binding_list> <binding> <optsemi>

<cbinding> ::= <"#private">
               <"#public">
               <"#protected">

<binding> ::= '.' <cbinding>
              <tag> ':' <exp>
              <tag> <symlist> ':' <exp>
              <tag> <error>

-- ============================================================
-- EXPRESSIONS
-- ============================================================

<exp> ::= <TAG>
          <FN_TAG>
          <OBJ_TAG>
          <qualified_tag>
          <SYMBOL>
          <self_evaluating>
          '(' <exp> ')'
          <sequence>

          -- Arithmetic
          <exp> <PLUS> <exp>
          <exp> <MINUS> <exp>
          <exp> <TIMES> <exp>
          <exp> <DIV> <exp>
          <exp> <MOD> <exp>
          <MINUS> <exp>
          <PLUS> <exp>

          -- Logical
          <exp> <AND_AND> <exp>
          <exp> <OR_OR> <exp>
          <BANG> <exp>

          -- Comparison
          <exp> <GREATER> <exp>
          <exp> <LESS> <exp>
          <exp> <GREATER_EQ> <exp>
          <exp> <LESS_EQ> <exp>
          <exp> <EQ> <exp>
          <exp> <EQ_EQ> <exp>
          <exp> <NOT_EQ> <exp>

          -- Function composition
          <exp> <COMPOSE> <exp>

          -- Pipe operator (left-to-right chaining)
          <exp> <PIPE> <exp>

          -- Flip (argument order)
          <FLIP> <exp>

          -- Indexing and slicing
          <exp> '[' <exp> ']'
          <exp> '[' <exp> '.' '.' <exp> ']'

          -- Function/method calls
          <fcall>

          -- Control flow
          <IF> <exp> <THEN> <exp> <ELSE> <exp>
          <IF> <exp> <THEN> <exp>
          <IF> <exp> <error>
          <WHILE> <exp> <DO> <exp>
          <WHILE> <exp> <error>
          <DO> <exp> <WHILE> <exp>
          <DO> <exp> <error>
          <RETURN> <exp>
          <RETURN>

          -- Lambda and currying
          <LAMBDA> <symlist> <exp>
          <LAMBDA> <error>
          <BACKSLASH> <singletag> <exp>
          <exp> <CURRY> <parmlist>

          -- Let bindings
          <LET> <letsymlist> <exp>

          -- Partial application (placeholder curry)
          <TIMES> <exp>

          -- Context operator
          <exp> <CONTEXT> <TAG>

          -- Property access and method calls
          <exp> '.' <TAG>
          <exp> '.' <TAG> <parmlist>
          <exp> '.' <qualified_tag>
          <exp> '.' <qualified_tag> <parmlist>

          -- Map/associative array literal
          <map>

          -- Pattern match expression
          <MATCH> <exp> <match_block>

-- ============================================================
-- MAPS (first-class associative arrays)
-- Syntax: %{key: val, key2: val2} or %{exp => exp, exp => exp}
-- ============================================================

<map> ::= '%' '{' '}'
          '%' '{' <maplist> '}'

<maplist> ::= <mapitem>
              <maplist> ',' <mapitem>

-- key: val for symbol keys, exp => exp for computed keys
<mapitem> ::= <TAG> ':' <exp>
              <exp> <ARROW> <exp>

-- ============================================================
-- HASH TABLES (legacy syntax, alias for maps)
-- ============================================================

<htlist> ::= [ <htlist2> ]

<htlist2> ::= <htlist2> ',' <htitem>
              <htitem>

<htitem> ::= <exp> ':' <exp>

-- ============================================================
-- PATTERN MATCHING
-- ============================================================

<match_block> ::= '{' <match_cases> '}'

<match_cases> ::= <match_case>
                  <match_cases> <match_case>

<match_case> ::= <pattern> <ARROW> <exp> <optsemi>
                 <pattern> <WHEN> <exp> <ARROW> <exp> <optsemi>

<pattern> ::= <TAG>
              <SYMBOL>
              <INT>
              <FLOAT>
              <STRING>
              '_'
              '[' <pattern_list> ']'
              '[' <pattern_list> '|' <TAG> ']'
              '%' '{' <pattern_maplist> '}'
              <TAG> '(' <pattern_list> ')'
              <pattern> <AS> <TAG>

<pattern_list> ::= [ <pattern> ]
                   [ <pattern_list> ',' <pattern> ]

<pattern_maplist> ::= [ <TAG> ':' <pattern> ]
                      [ <pattern_maplist> ',' <TAG> ':' <pattern> ]

-- ============================================================
-- FUNCTION CALLS AND CURRYING
-- All functions are automatically curried:
--   f(a, b, c) can be called as f(a)(b)(c) or f(a, b)(c)
-- Placeholder _ for partial application:
--   add(_, 5) returns a function awaiting first argument
-- ============================================================

<fcall> ::= <TAG> <parmlist>
            <FN_TAG> <parmlist>
            <SYMBOL> <parmlist>
            <qualified_tag> <parmlist>
            <exp> <parmlist>

<parmlist> ::= '(' <vexp_seq> ')'
               '(' ')'

<vexp_seq> ::= <exp>
               '_'
               <vexp_seq> ',' <exp>
               <vexp_seq> ',' '_'

-- ============================================================
-- SYMBOL/TAG LISTS
-- ============================================================

<tag> ::= <TAG>

<singletag> ::= <TAG>

<symlist> ::= '(' <symseq> ')'
              '(' ')'

<symseq> ::= <TAG>
             <symseq> ',' <TAG>
             <symseq> <TAG>
             <symseq> <error>

-- ============================================================
-- LET BINDINGS (with destructuring)
-- ============================================================

<letsymlist> ::= '(' <letsymseq> ')'
                 '(' ')'

<letsymseq> ::= <letsym>
                <letsymseq> ',' <letsym>
                <letsymseq> <letsym>
                <letsymseq> <error>

<letsym> ::= <TAG>
             <TAG> <EQ> <exp>
             <pattern> <EQ> <exp>

-- ============================================================
-- SEQUENCES (statement blocks)
-- ============================================================

<sequence> ::= '{' <sequence_seq> '}'

<sequence_seq> ::= <exp>
                   <sequence_seq> ';' <exp>
                   <sequence_seq> ';'
                   <sequence_seq> <error>

-- ============================================================
-- LISTS
-- ============================================================

<list> ::= '[' <list_exp> ']'
           '[' ']'
           '[' <exp> '|' <exp> ']'

<list_exp> ::= <exp>
               <list_exp> ',' <exp>

-- ============================================================
-- SELF-EVALUATING LITERALS
-- ============================================================

<self_evaluating> ::= <INT>
                      <FLOAT>
                      <STRING>
                      <T_ARGS>
                      <T_SELF>
                      <T_PARENT>
                      <T_CALLER>
                      <T_USER>
                      <T_NULL>
                      <T_FUN>
                      <list>
                      <map>
                      <T_HTABLE> '(' <htlist> ')'
                      <T_HTABLE> <INT> '(' <htlist> ')'

-- ============================================================
-- OMETA-STYLE GRAMMAR DEFINITIONS
-- Grammars are first-class objects that can parse/transform data
-- ============================================================

<grammar_def> ::= <GRAMMAR> <qualified_tag> <grammar_inheritance> '{' <grammar_rules> '}'

<grammar_inheritance> ::= [ '<:' <qualified_tag> ]

<grammar_rules> ::= <grammar_rule>
                    <grammar_rules> <grammar_rule>

<grammar_rule> ::= <TAG> <rule_params> '=' <rule_body> <optsemi>

<rule_params> ::= [ '(' <symseq> ')' ]

-- Rule body is a parsing expression (PEG-style)
<rule_body> ::= <rule_alt>

<rule_alt> ::= <rule_seq>
               <rule_alt> '|' <rule_seq>

<rule_seq> ::= <rule_term>
               <rule_seq> <rule_term>

<rule_term> ::= <rule_primary>
                <rule_primary> '*'
                <rule_primary> '+'
                <rule_primary> '?'
                '~' <rule_primary>
                '&' <rule_primary>
                '!' <rule_primary>

<rule_primary> ::= <TAG>
                   <STRING>
                   <CHAR_RANGE>
                   '.'
                   '(' <rule_body> ')'
                   '[' <rule_body> ']'
                   '<' <TAG> '>'
                   '<' <TAG> <parmlist> '>'
                   ':' <TAG>
                   '{' <exp> '}'
                   <ARROW> <exp>

-- ============================================================
-- ADDITIONAL TOKENS
-- ============================================================

-- <PIPE> ::= '|>'
-- <ARROW> ::= '=>'
-- <CURRY> ::= '@'
-- <MATCH> ::= 'match'
-- <WHEN> ::= 'when'
-- <AS> ::= 'as'
-- <GRAMMAR> ::= 'grammar'
-- <CHAR_RANGE> ::= 'a'..'z' style range literals
